{{- if eq .Values.global.deploymentTarget "kubernetes" }}
{{- range $route := .Values.routes }}
{{- if eq ($route.enabled | toString) "true" }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-%s" (include "application.fullname" $) $route.name | trimSuffix "-" }}
  labels:
    {{- include "application.labels" $ | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: '32k'
    nginx.ingress.kubernetes.io/proxy-buffers-number: '8'
  {{- if not $.Values.oauth2Proxy.enabled }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: 'true'
  {{- end }}
spec:
  tls:
    - hosts:
      - {{ $route.host }}
      secretName: tls-secret
  rules:
    - host: {{ $route.host }}
      http:
        paths:
          {{- if $.Values.oauth2Proxy.enabled }}
          - path: /
          {{- else }}
          - path: {{ $route.path }}(.*)
          {{- end }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "application.fullname" $ }}
                port:
                  {{- if $.Values.oauth2Proxy.enabled }}
                  name: oauth2proxy
                  {{- else }}
                  name: http
                  {{- end }}
{{- end }}
{{- end }}
{{- end }}
