{{- range $volume := .Values.volumes }}
{{- if eq $volume.type "pvc" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "application.fullname" $ }}-{{ $volume.name }}
  labels:
    {{- include "application.labels" $ | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $volume.storageRequest | default "1Gi" }}
{{- end }}
{{- end }}
