{{- range $volume := .Values.volumes }}
{{- if eq $volume.type "secret" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" $ }}-{{ $volume.name }}
  labels:
    {{- include "application.labels" $ | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    helm.sh/hook: "pre-install"
    helm.sh/hook-delete-policy: "before-hook-creation"
type: Opaque
data:
  {{- $volume.data | toYaml | nindent 2 }}
{{- end }}
{{- end }}
