apiVersion: v1
kind: Service
metadata:
  name: {{ include "application.fullname" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
  {{- if and (.Values.oauth2Proxy.enabled) (eq .Values.global.deploymentTarget "openshift") (eq .Values.oauth2Proxy.provider "azure") }}
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: {{ include "application.fullname" . }}-tls
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if (.Values.oauth2Proxy.enabled) }}
      targetPort: oauth2proxy
      {{- else }}
      targetPort: http
      {{- end }}
      name: web
  selector:
    {{- include "application.selectorLabels" . | nindent 4 }}
